// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyorderDatabase;

#nullable disable

namespace WEBAPI.Migrations.MyOrdersDb
{
    [DbContext(typeof(MyOrdersDbContext))]
    partial class MyOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyorderModule.FinalCart", b =>
                {
                    b.Property<int>("orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderid"));

                    b.Property<Guid?>("MyOrdersid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("imageurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productcount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderid");

                    b.HasIndex("MyOrdersid");

                    b.ToTable("Orderedcart");
                });

            modelBuilder.Entity("MyorderModule.MyOrders", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cvvnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliverydate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paiddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentmode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upicode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Orderdata");
                });

            modelBuilder.Entity("Userdata.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ApartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MyOrdersid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MyOrdersid");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("MyorderModule.FinalCart", b =>
                {
                    b.HasOne("MyorderModule.MyOrders", null)
                        .WithMany("product")
                        .HasForeignKey("MyOrdersid");
                });

            modelBuilder.Entity("Userdata.Address", b =>
                {
                    b.HasOne("MyorderModule.MyOrders", null)
                        .WithMany("address")
                        .HasForeignKey("MyOrdersid");
                });

            modelBuilder.Entity("MyorderModule.MyOrders", b =>
                {
                    b.Navigation("address");

                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
